from struct import *
import socket


class DeviceID():
  
  def __init__(self):
    self.Length=None
    self.EncapsulationVersion=None
    self.Address=None
    self.VendorID=None
    self.Vendor=None
    self.DeviceID=None
    self.DeviceType=""
    self.ProductCode=None
    self.Revision=None
    self.Status=None
    self.SerialNumber=None
    self.ProductNameLength=None
    self.ProductName=""
    self.State=None
    
  def WhosThere(self, data):
    self.Length=unpack_from('<H', data, 28)[0]
    self.EncapsulationVersion=unpack_from('<H', data, 30)[0]
    
    longIP=unpack_from('<I', data, 36)[0]
    self.Address=socket.inet_ntoa(pack('<L', longIP))
    
    self.VendorID=unpack_from('<H', data, 48)[0]
    self.Vendor=VendorNames(self.VendorID)
    
    self.DeviceID=unpack_from('<H', data, 50)[0]
    self.DeviceType=DeviceTypes(self.DeviceID)
    self.ProductCode=unpack_from('<H', data, 52)[0]
    
    major=unpack_from('<B', data, 54)[0]
    minor=unpack_from('<B', data, 55)[0]
    self.Revision=str(major) + '.' + str(minor)
    
    self.Status=unpack_from('<H', data, 56)[0]
    self.SerialNumber=unpack_from('<I', data, 58)[0]
    self.ProductNameLength=unpack_from('<B', data, 62)[0]
    self.ProductName=data[63:63+self.ProductNameLength]
    self.State=unpack_from('<B', data, self.Length+self.ProductNameLength+1)[0]
    
    return self

def _buildListIdentity():
  ListService=0x63
  ListLength=0x00
  ListSessionHandle=0x00
  ListStatus=0x00
  ListResponse=0x00
  ListContext1=0x00
  ListContext2=0x00
  ListContext3=0x00
  ListOptions=0x00
  
  return pack("<HHIIHHHHI",
	      ListService,
	      ListLength,
	      ListSessionHandle,
	      ListStatus,
	      ListResponse,
	      ListContext1,
	      ListContext2,
	      ListContext3,
	      ListOptions)

def ListIdentity():
  stuff=[]
  request=_buildListIdentity()
  s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  s.settimeout(0.5)
  s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
  s.sendto(request, ('255.255.255.255', 44818))
  try:
    while(1):
      ret=s.recv(1024)
      stuff.append(DeviceID().WhosThere(ret))
  except:
      do="Nothing"
  return stuff


# List originally came from Wireshark /epan/dissectors/packet-cip.c
def DeviceTypes(deviceID):
  if deviceID==0x00: return "Generic Device (deprecated)"
  if deviceID==0x02: return "AC Drive"
  if deviceID==0x03: return "Motor Overload"
  if deviceID==0x04: return "Limit Switch"
  if deviceID==0x05: return "Inductive Proximity Switch"
  if deviceID==0x06: return "Photoelectric Sensor"
  if deviceID==0x07: return "General Purpose Discrete I/O"
  if deviceID==0x09: return "Resolver"
  if deviceID==0x0C: return "Communications Adapter"
  if deviceID==0x0E: return "Programmable Logic Controller"
  if deviceID==0x10: return "Position Controller"
  if deviceID==0x13: return "DC Drive"
  if deviceID==0x15: return "Contactor"
  if deviceID==0x16: return "Motor Starter"
  if deviceID==0x17: return "Soft Start"
  if deviceID==0x18: return "Human-Machine Interface"
  if deviceID==0x1A: return "Mass Flow Controller"
  if deviceID==0x1B: return "Pneumatic Valve"
  if deviceID==0x1C: return "Vacuum Pressure Gauge"
  if deviceID==0x1D: return "Process Control Value"
  if deviceID==0x1E: return "Residual Gas Analyzer"
  if deviceID==0x1F: return "DC Power Generator"
  if deviceID==0x20: return "RF Power Generator"
  if deviceID==0x21: return "Turbomolecular Vacuum Pump"
  if deviceID==0x22: return "Encoder"
  if deviceID==0x23: return "Safety Discrete I/O Device"
  if deviceID==0x24: return "Fluid Flow Controller"
  if deviceID==0x25: return "CIP Motion Drive"
  if deviceID==0x26: return "CompoNet Repeater"
  if deviceID==0x27: return "Mass Flow Controller, Enhanced"
  if deviceID==0x28: return "CIP Modbus Device"
  if deviceID==0x29: return "CIP Modbus Translator"
  if deviceID==0x2A: return "Safety Analog I/O Device"
  if deviceID==0x2B: return "Generic Device (keyable)"
  if deviceID==0x2C: return "Managed Switch"
  if deviceID==0x32: return "ControlNet Physical Layer Component"

# List originally came from Wireshark /epan/dissectors/packet-cip.c
def VendorNames(vid):  
  if vid==0: return "Reserved"
  if vid==1: return "Rockwell Automation/Allen-Bradley"
  if vid==2: return "Namco Controls Corp."
  if vid==3: return "Honeywell Inc."
  if vid==4: return "Parker Hannifin Corp. (Veriflo Division)"
  if vid==5: return "Rockwell Automation/Reliance Elec."
  if vid==6: return "Reserved"
  if vid==7: return "SMC Corporation"
  if vid==8: return "Molex Incorporated"
  if vid==9: return "Western Reserve Controls Corp."
  if vid==10: return "Advanced Micro Controls Inc. (AMCI)"
  if vid==11: return "ASCO Pneumatic Controls"
  if vid==12: return "Banner Engineering Corp."
  if vid==13: return "Belden Wire & Cable Company"
  if vid==14: return "Cooper Interconnect"
  if vid==15: return "Reserved"
  if vid==16: return "Daniel Woodhead Co. (Woodhead Connectivity)"
  if vid==17: return "Dearborn Group Inc."
  if vid==18: return "Reserved"
  if vid==19: return "Helm Instrument Company"
  if vid==20: return "Huron Net Works"
  if vid==21: return "Lumberg, Inc."
  if vid==22: return "Online Development Inc.(Automation Value)"
  if vid==23: return "Vorne Industries, Inc."
  if vid==24: return "ODVA Special Reserve"
  if vid==25: return "Reserved"
  if vid==26: return "Festo Corporation"
  if vid==27: return "Reserved"
  if vid==28: return "Reserved"
  if vid==29: return "Reserved"
  if vid==30: return "Unico, Inc."
  if vid==31: return "Ross Controls"
  if vid==32: return "Reserved"
  if vid==33: return "Reserved"
  if vid==34: return "Hohner Corp."
  if vid==35: return "Micro Mo Electronics, Inc."
  if vid==36: return "MKS Instruments, Inc."
  if vid==37: return "Yaskawa Electric America formerly Magnetek Drives"
  if vid==38: return "Reserved"
  if vid==39: return "AVG Automation (Uticor)"
  if vid==40: return "Wago Corporation"
  if vid==41: return "Kinetics (Unit Instruments)"
  if vid==42: return "IMI Norgren Limited"
  if vid==43: return "BALLUFF, Inc."
  if vid==44: return "Yaskawa Electric America, Inc."
  if vid==45: return "Eurotherm Controls Inc"
  if vid==46: return "ABB Industrial Systems"
  if vid==47: return "Omron Corporation"
  if vid==48: return "TURCk, Inc."
  if vid==49: return "Grayhill Inc."
  if vid==50: return "Real Time Automation (C&ID)"
  if vid==51: return "Reserved"
  if vid==52: return "Numatics, Inc."
  if vid==53: return "Lutze, Inc."
  if vid==54: return "Reserved"
  if vid==55: return "Reserved"
  if vid==56: return "Softing GmbH"
  if vid==57: return "Pepperl + Fuchs"
  if vid==58: return "Spectrum Controls, Inc."
  if vid==59: return "D.I.P. Inc. MKS Inst."
  if vid==60: return "Applied Motion Products, Inc."
  if vid==61: return "Sencon Inc."
  if vid==62: return "High Country Tek"
  if vid==63: return "SWAC Automation Consult GmbH"
  if vid==64: return "Clippard Instrument Laboratory"
  if vid==65: return "Reserved"
  if vid==66: return "Reserved"
  if vid==67: return "Reserved"
  if vid==68: return "Eaton Electrical"
  if vid==69: return "Reserved"
  if vid==70: return "Reserved"
  if vid==71: return "Toshiba International Corp."
  if vid==72: return "Control Technology Incorporated"
  if vid==73: return "TCS (NZ) Ltd."
  if vid==74: return "Hitachi, Ltd."
  if vid==75: return "ABB Robotics Products AB"
  if vid==76: return "NKE Corporation"
  if vid==77: return "Rockwell Software, Inc."
  if vid==78: return "Escort Memory Systems (A Datalogic Group Co.)"
  if vid==79: return "Reserved"
  if vid==80: return "Industrial Devices Corporation"
  if vid==81: return "IXXAT Automation GmbH"
  if vid==82: return "Mitsubishi Electric Automation, Inc."
  if vid==83: return "OPTO-22"
  if vid==84: return "Reserved"
  if vid==85: return "Reserved"
  if vid==86: return "Horner Electric"
  if vid==87: return "Burkert Werke GmbH & Co. KG"
  if vid==88: return "Reserved"
  if vid==89: return "Industrial Indexing Systems, Inc."
  if vid==90: return "HMS Industrial Networks AB"
  if vid==91: return "Robicon"
  if vid==92: return "Helix Technology (Granville-Phillips)"
  if vid==93: return "Arlington Laboratory"
  if vid==94: return "Advantech Co. Ltd."
  if vid==95: return "Square D Company"
  if vid==96: return "Digital Electronics Corp."
  if vid==97: return "Danfoss"
  if vid==98: return "Reserved"
  if vid==99: return "Reserved"
  if vid==100: return "Bosch Rexroth Corporation, Pneumatics"
  if vid==101: return "Applied Materials, Inc."
  if vid==102: return "Showa Electric Wire & Cable Co."
  if vid==103: return "Pacific Scientific (API Controls Inc.)"
  if vid==104: return "Sharp Manufacturing Systems Corp."
  if vid==105: return "Olflex Wire & Cable, Inc."
  if vid==106: return "Reserved"
  if vid==107: return "Unitrode"
  if vid==108: return "Beckhoff Automation GmbH"
  if vid==109: return "National Instruments"
  if vid==110: return "Mykrolis Corporations (Millipore)"
  if vid==111: return "International Motion Controls Corp."
  if vid==112: return "Reserved"
  if vid==113: return "SEG Kempen GmbH"
  if vid==114: return "Reserved"
  if vid==115: return "Reserved"
  if vid==116: return "MTS Systems Corp."
  if vid==117: return "Krones, Inc"
  if vid==118: return "Reserved"
  if vid==119: return "EXOR Electronic R & D"
  if vid==120: return "SIEI S.p.A."
  if vid==121: return "KUKA Roboter GmbH"
  if vid==122: return "Reserved"
  if vid==123: return "SEC (Samsung Electronics Co., Ltd)"
  if vid==124: return "Binary Electronics Ltd"
  if vid==125: return "Flexible Machine Controls"
  if vid==126: return "Reserved"
  if vid==127: return "ABB Inc. (Entrelec)"
  if vid==128: return "MAC Valves, Inc."
  if vid==129: return "Auma Actuators Inc"
  if vid==130: return "Toyoda Machine Works, Ltd"
  if vid==131: return "Reserved"
  if vid==132: return "Reserved"
  if vid==133: return "Balogh T.A.G., Corporation"
  if vid==134: return "TR Systemtechnik GmbH"
  if vid==135: return "UNIPULSE Corporation"
  if vid==136: return "Reserved"
  if vid==137: return "Reserved"
  if vid==138: return "Conxall Corporation Inc."
  if vid==139: return "Reserved"
  if vid==140: return "Reserved"
  if vid==141: return "Kuramo Electric Co., Ltd."
  if vid==142: return "Creative Micro Designs"
  if vid==143: return "GE Industrial Systems"
  if vid==144: return "Leybold Vacuum GmbH"
  if vid==145: return "Siemens Energy & Automation/Drives"
  if vid==146: return "Kodensha Ltd"
  if vid==147: return "Motion Engineering, Inc."
  if vid==148: return "Honda Engineering Co., Ltd"
  if vid==149: return "EIM Valve Controls"
  if vid==150: return "Melec Inc."
  if vid==151: return "Sony Manufacturing Systems Corporation"
  if vid==152: return "North American Mfg."
  if vid==153: return "WATLOW"
  if vid==154: return "Japan Radio Co., Ltd"
  if vid==155: return "NADEX Co., Ltd"
  if vid==156: return "Ametek Automation & Process Technologies"
  if vid==157: return "Reserved"
  if vid==158: return "KVASER AB"
  if vid==159: return "IDEC IZUMI Corporation"
  if vid==160: return "Mitsubishi Heavy Industries Ltd"
  if vid==161: return "Mitsubishi Electric Corporation"
  if vid==162: return "Horiba-STEC Inc."
  if vid==163: return "esd electronic system design gmbh"
  if vid==164: return "DAIHEN Corporation"
  if vid==165: return "Tyco Valves & Controls/Keystone"
  if vid==166: return "EBARA Corporation"
  if vid==167: return "Reserved"
  if vid==168: return "Reserved"
  if vid==169: return "Hokuyo Electric Co. Ltd"
  if vid==170: return "Pyramid Solutions, Inc."
  if vid==171: return "Denso Wave Incorporated"
  if vid==172: return "HLS Hard-Line Solutions Inc"
  if vid==173: return "Caterpillar, Inc."
  if vid==174: return "PDL Electronics Ltd."
  if vid==175: return "Reserved"
  if vid==176: return "Red Lion Controls"
  if vid==177: return "ANELVA Corporation"
  if vid==178: return "Toyo Denki Seizo KK"
  if vid==179: return "Sanyo Denki Co., Ltd"
  if vid==180: return "Advanced Energy Japan K.K. (Aera Japan)"
  if vid==181: return "Pilz GmbH & Co"
  if vid==182: return "Marsh Bellofram-Bellofram PCD Division"
  if vid==183: return "Reserved"
  if vid==184: return "M-SYSTEM Co. Ltd"
  if vid==185: return "Nissin Electric Co., Ltd"
  if vid==186: return "Hitachi Metals Ltd."
  if vid==187: return "Oriental Motor Company"
  if vid==188: return "A&D Co., Ltd"
  if vid==189: return "Phasetronics, Inc."
  if vid==190: return "Cummins Engine Company"
  if vid==191: return "Deltron Inc."
  if vid==192: return "Geneer Corporation"
  if vid==193: return "Anatol Automation, Inc."
  if vid==194: return "Reserved"
  if vid==195: return "Reserved"
  if vid==196: return "Medar, Inc."
  if vid==197: return "Comdel Inc."
  if vid==198: return "Advanced Energy Industries, Inc"
  if vid==199: return "Reserved"
  if vid==200: return "DAIDEN Co., Ltd"
  if vid==201: return "CKD Corporation"
  if vid==202: return "Toyo Electric Corporation"
  if vid==203: return "Reserved"
  if vid==204: return "AuCom Electronics Ltd"
  if vid==205: return "Shinko Electric Co., Ltd"
  if vid==206: return "Vector Informatik GmbH"
  if vid==207: return "Reserved"
  if vid==208: return "Moog Inc."
  if vid==209: return "Contemporary Controls"
  if vid==210: return "Tokyo Sokki Kenkyujo Co., Ltd"
  if vid==211: return "Schenck-AccuRate, Inc."
  if vid==212: return "The Oilgear Company"
  if vid==213: return "Reserved"
  if vid==214: return "ASM Japan K.K."
  if vid==215: return "HIRATA Corp."
  if vid==216: return "SUNX Limited"
  if vid==217: return "Meidensha Corp."
  if vid==218: return "NIDEC SANKYO CORPORATION (Sankyo Seiki Mfg. Co., Ltd)"
  if vid==219: return "KAMRO Corp."
  if vid==220: return "Nippon System Development Co., Ltd"
  if vid==221: return "EBARA Technologies Inc."
  if vid==222: return "Reserved"
  if vid==223: return "Reserved"
  if vid==224: return "SG Co., Ltd"
  if vid==225: return "Vaasa Institute of Technology"
  if vid==226: return "MKS Instruments (ENI Technology)"
  if vid==227: return "Tateyama System Laboratory Co., Ltd."
  if vid==228: return "QLOG Corporation"
  if vid==229: return "Matric Limited Inc."
  if vid==230: return "NSD Corporation"
  if vid==231: return "Reserved"
  if vid==232: return "Sumitomo Wiring Systems, Ltd"
  if vid==233: return "Group 3 Technology Ltd"
  if vid==234: return "CTI Cryogenics"
  if vid==235: return "POLSYS CORP"
  if vid==236: return "Ampere Inc."
  if vid==237: return "Reserved"
  if vid==238: return "Simplatroll Ltd"
  if vid==239: return "Reserved"
  if vid==240: return "Reserved"
  if vid==241: return "Leading Edge Design"
  if vid==242: return "Humphrey Products"
  if vid==243: return "Schneider Automation, Inc."
  if vid==244: return "Westlock Controls Corp."
  if vid==245: return "Nihon Weidmuller Co., Ltd"
  if vid==246: return "Brooks Instrument (Div. of Emerson)"
  if vid==247: return "Reserved"
  if vid==248: return " Moeller GmbH"
  if vid==249: return "Varian Vacuum Products"
  if vid==250: return "Yokogawa Electric Corporation"
  if vid==251: return "Electrical Design Daiyu Co., Ltd"
  if vid==252: return "Omron Software Co., Ltd"
  if vid==253: return "BOC Edwards"
  if vid==254: return "Control Technology Corporation"
  if vid==255: return "Bosch Rexroth"
  if vid==256: return "Turck"
  if vid==257: return "Control Techniques PLC"
  if vid==258: return "Hardy Instruments, Inc."
  if vid==259: return "LS Industrial Systems"
  if vid==260: return "E.O.A. Systems Inc."
  if vid==261: return "Reserved"
  if vid==262: return "New Cosmos Electric Co., Ltd."
  if vid==263: return "Sense Eletronica LTDA"
  if vid==264: return "Xycom, Inc."
  if vid==265: return "Baldor Electric"
  if vid==266: return "Reserved"
  if vid==267: return "Patlite Corporation"
  if vid==268: return "Reserved"
  if vid==269: return "Mogami Wire & Cable Corporation"
  if vid==270: return "Welding Technology Corporation (WTC)"
  if vid==271: return "Reserved"
  if vid==272: return "Deutschmann Automation GmbH"
  if vid==273: return "ICP Panel-Tec Inc."
  if vid==274: return "Bray Controls USA"
  if vid==275: return "Reserved"
  if vid==276: return "Status Technologies"
  if vid==277: return "Trio Motion Technology Ltd"
  if vid==278: return "Sherrex Systems Ltd"
  if vid==279: return "Adept Technology, Inc."
  if vid==280: return "Spang Power Electronics"
  if vid==281: return "Reserved"
  if vid==282: return "Acrosser Technology Co., Ltd"
  if vid==283: return "Hilscher GmbH"
  if vid==284: return "IMAX Corporation"
  if vid==285: return "Electronic Innovation, Inc. (Falter Engineering)"
  if vid==286: return "Netlogic Inc."
  if vid==287: return "Bosch Rexroth Corporation, Indramat"
  if vid==288: return "Reserved"
  if vid==289: return "Reserved"
  if vid==290: return "Murata  Machinery Ltd."
  if vid==291: return "MTT Company Ltd."
  if vid==292: return "Kanematsu Semiconductor Corp."
  if vid==293: return "Takebishi Electric Sales Co."
  if vid==294: return "Tokyo Electron Device Ltd"
  if vid==295: return "PFU Limited"
  if vid==296: return "Hakko Automation Co., Ltd."
  if vid==297: return "Advanet Inc."
  if vid==298: return "Tokyo Electron Software Technologies Ltd."
  if vid==299: return "Reserved"
  if vid==300: return "Shinagawa Electric Wire Co., Ltd."
  if vid==301: return "Yokogawa M&C Corporation"
  if vid==302: return "KONAN Electric Co., Ltd."
  if vid==303: return "Binar Elektronik AB"
  if vid==304: return "Furukawa Electric Co."
  if vid==305: return "Cooper Energy Services"
  if vid==306: return "Schleicher GmbH & Co."
  if vid==307: return "Hirose Electric Co., Ltd"
  if vid==308: return "Western Servo Design Inc."
  if vid==309: return "Prosoft Technology"
  if vid==310: return "Reserved"
  if vid==311: return "Towa Shoko Co., Ltd"
  if vid==312: return "Kyopal Co., Ltd"
  if vid==313: return "Extron Co."
  if vid==314: return "Wieland Electric GmbH"
  if vid==315: return "SEW Eurodrive GmbH"
  if vid==316: return "Aera Corporation"
  if vid==317: return "STA Reutlingen"
  if vid==318: return "Reserved"
  if vid==319: return "Fuji Electric Co., Ltd."
  if vid==320: return "Reserved"
  if vid==321: return "Reserved"
  if vid==322: return "ifm efector, inc."
  if vid==323: return "Reserved"
  if vid==324: return "IDEACOD-Hohner Automation S.A."
  if vid==325: return "CommScope Inc."
  if vid==326: return "GE Fanuc Automation North America, Inc."
  if vid==327: return "Matsushita Electric Industrial Co., Ltd"
  if vid==328: return "Okaya Electronics Corporation"
  if vid==329: return "KASHIYAMA Industries, Ltd"
  if vid==330: return "JVC"
  if vid==331: return "Interface Corporation"
  if vid==332: return "Grape Systems Inc."
  if vid==333: return "Reserved"
  if vid==334: return "Reserved"
  if vid==335: return "Toshiba IT & Control Systems Corporation"
  if vid==336: return "Sanyo Machine Works, Ltd."
  if vid==337: return "Vansco Electronics Ltd."
  if vid==338: return "Dart Container Corp."
  if vid==339: return "Livingston & Co., Inc."
  if vid==340: return "Alfa Laval LKM as"
  if vid==341: return "BF ENTRON Ltd. (British Federal)"
  if vid==342: return "Bekaert Engineering NV"
  if vid==343: return "Ferran  Scientific Inc."
  if vid==344: return "KEBA AG"
  if vid==345: return "Endress + Hauser"
  if vid==346: return "Reserved"
  if vid==347: return "ABB ALSTOM Power UK Ltd. (EGT)"
  if vid==348: return "Berger Lahr GmbH"
  if vid==349: return "Reserved"
  if vid==350: return "Federal Signal Corp."
  if vid==351: return "Kawasaki Robotics (USA), Inc."
  if vid==352: return "Bently Nevada Corporation"
  if vid==353: return "Reserved"
  if vid==354: return "FRABA Posital GmbH"
  if vid==355: return "Elsag Bailey, Inc."
  if vid==356: return "Fanuc Robotics America"
  if vid==357: return "Reserved"
  if vid==358: return "Surface Combustion, Inc."
  if vid==359: return "Reserved"
  if vid==360: return "AILES Electronics Ind. Co., Ltd."
  if vid==361: return "Wonderware Corporation"
  if vid==362: return "Particle Measuring Systems, Inc."
  if vid==363: return "Reserved"
  if vid==364: return "Reserved"
  if vid==365: return "BITS Co., Ltd"
  if vid==366: return "Japan Aviation Electronics Industry Ltd"
  if vid==367: return "Keyence Corporation"
  if vid==368: return "Kuroda Precision Industries Ltd."
  if vid==369: return "Mitsubishi Electric Semiconductor Application"
  if vid==370: return "Nippon Seisen Cable, Ltd."
  if vid==371: return "Omron ASO Co., Ltd"
  if vid==372: return "Seiko Seiki Co., Ltd."
  if vid==373: return "Sumitomo Heavy Industries, Ltd."
  if vid==374: return "Tango Computer Service Corporation"
  if vid==375: return "Technology Service, Inc."
  if vid==376: return "Toshiba Information Systems (Japan) Corporation"
  if vid==377: return "TOSHIBA Schneider Inverter Corporation"
  if vid==378: return "Toyooki Kogyo Co., Ltd."
  if vid==379: return "XEBEC"
  if vid==380: return "Madison Cable Corporation"
  if vid==381: return "Hitati Engineering & Services Co., Ltd"
  if vid==382: return "TEM-TECH Lab Co., Ltd"
  if vid==383: return "International Laboratory Corporation"
  if vid==384: return "Dyadic Systems Co., Ltd."
  if vid==385: return "SETO Electronics Industry Co., Ltd"
  if vid==386: return "Tokyo Electron Kyushu Limited"
  if vid==387: return "KEI System Co., Ltd"
  if vid==388: return "Reserved"
  if vid==389: return "Asahi Engineering Co., Ltd"
  if vid==390: return "Contrex Inc."
  if vid==391: return "Paradigm Controls Ltd."
  if vid==392: return "Reserved"
  if vid==393: return "Ohm Electric Co., Ltd."
  if vid==394: return "RKC Instrument Inc."
  if vid==395: return "Suzuki Motor Corporation"
  if vid==396: return "Custom Servo Motors Inc."
  if vid==397: return "PACE Control Systems"
  if vid==398: return "Reserved"
  if vid==399: return "Reserved"
  if vid==400: return "LINTEC Co., Ltd."
  if vid==401: return "Hitachi Cable Ltd."
  if vid==402: return "BUSWARE Direct"
  if vid==403: return "Eaton Electric B.V. (former Holec Holland N.V.)"
  if vid==404: return "VAT Vakuumventile AG"
  if vid==405: return "Scientific Technologies Incorporated"
  if vid==406: return "Alfa Instrumentos Eletronicos Ltda"
  if vid==407: return "TWK Elektronik GmbH"
  if vid==408: return "ABB Welding Systems AB"
  if vid==409: return "BYSTRONIC Maschinen AG"
  if vid==410: return "Kimura Electric Co., Ltd"
  if vid==411: return "Nissei Plastic Industrial Co., Ltd"
  if vid==412: return "Reserved"
  if vid==413: return "Kistler-Morse Corporation"
  if vid==414: return "Proteous Industries Inc."
  if vid==415: return "IDC Corporation"
  if vid==416: return "Nordson Corporation"
  if vid==417: return "Rapistan Systems"
  if vid==418: return "LP-Elektronik GmbH"
  if vid==419: return "GERBI & FASE S.p.A.(Fase Saldatura)"
  if vid==420: return "Phoenix Digital Corporation"
  if vid==421: return "Z-World Engineering"
  if vid==422: return "Honda R&D Co., Ltd."
  if vid==423: return "Bionics Instrument Co., Ltd."
  if vid==424: return "Teknic, Inc."
  if vid==425: return "R.Stahl, Inc."
  if vid==426: return "Reserved"
  if vid==427: return "Ryco Graphic Manufacturing Inc."
  if vid==428: return "Giddings & Lewis, Inc."
  if vid==429: return "Koganei Corporation"
  if vid==430: return "Reserved"
  if vid==431: return "Nichigoh Communication Electric Wire Co., Ltd."
  if vid==432: return "Reserved"
  if vid==433: return "Fujikura Ltd."
  if vid==434: return "AD Link Technology Inc."
  if vid==435: return "StoneL Corporation"
  if vid==436: return "Computer Optical Products, Inc."
  if vid==437: return "CONOS Inc."
  if vid==438: return "Erhardt + Leimer GmbH"
  if vid==439: return "UNIQUE Co. Ltd"
  if vid==440: return "Roboticsware, Inc."
  if vid==441: return "Nachi Fujikoshi Corporation"
  if vid==442: return "Hengstler GmbH"
  if vid==443: return "Reserved"
  if vid==444: return "SUNNY GIKEN Inc."
  if vid==445: return "Lenze Drive Systems GmbH"
  if vid==446: return "CD Systems B.V."
  if vid==447: return "FMT/Aircraft Gate Support Systems AB"
  if vid==448: return "Axiomatic Technologies Corp"
  if vid==449: return "Embedded System Products, Inc."
  if vid==450: return "Reserved"
  if vid==451: return "Mencom Corporation"
  if vid==452: return "Reserved"
  if vid==453: return "Matsushita Welding Systems Co., Ltd."
  if vid==454: return "Dengensha Mfg. Co. Ltd."
  if vid==455: return "Quinn Systems Ltd."
  if vid==456: return "Tellima Technology Ltd"
  if vid==457: return "MDT, Software"
  if vid==458: return "Taiwan Keiso Co., Ltd"
  if vid==459: return "Pinnacle Systems"
  if vid==460: return "Ascom Hasler Mailing Sys"
  if vid==461: return "INSTRUMAR Limited"
  if vid==462: return "Reserved"
  if vid==463: return "Navistar International Transportation Corp"
  if vid==464: return "Huettinger Elektronik GmbH + Co. KG"
  if vid==465: return "OCM Technology Inc."
  if vid==466: return "Professional Supply Inc."
  if vid==467: return "Control Solutions"
  if vid==468: return "Baumer IVO GmbH & Co. KG"
  if vid==469: return "Worcester Controls Corporation"
  if vid==470: return "Pyramid Technical Consultants, Inc."
  if vid==471: return "Reserved"
  if vid==472: return "Apollo Fire Detectors Limited"
  if vid==473: return "Avtron Manufacturing, Inc."
  if vid==474: return "Reserved"
  if vid==475: return "Tokyo Keiso Co., Ltd."
  if vid==476: return "Daishowa Swiki Co., Ltd."
  if vid==477: return "Kojima Instruments Inc."
  if vid==478: return "Shimadzu Corporation"
  if vid==479: return "Tatsuta Electric Wire & Cable Co., Ltd."
  if vid==480: return "MECS Corporation"
  if vid==481: return "Tahara Electric"
  if vid==482: return "Koyo Electronics"
  if vid==483: return "Clever Devices"
  if vid==484: return "GCD Hardware & Software GmbH"
  if vid==485: return "Reserved"
  if vid==486: return "Miller Electric Mfg Co."
  if vid==487: return "GEA Tuchenhagen GmbH"
  if vid==488: return "Riken Keiki Co., LTD"
  if vid==489: return "Keisokugiken Corporation"
  if vid==490: return "Fuji Machine Mfg. Co., Ltd"
  if vid==491: return "Reserved"
  if vid==492: return "Nidec-Shimpo Corp."
  if vid==493: return "UTEC Corporation"
  if vid==494: return "Sanyo Electric Co. Ltd."
  if vid==495: return "Reserved"
  if vid==496: return "Reserved"
  if vid==497: return "Okano Electric Wire Co. Ltd"
  if vid==498: return "Shimaden Co. Ltd."
  if vid==499: return "Teddington Controls Ltd"
  if vid==500: return "Reserved"
  if vid==501: return "VIPA GmbH"
  if vid==502: return "Warwick Manufacturing Group"
  if vid==503: return "Danaher Controls"
  if vid==504: return "Reserved"
  if vid==505: return "Reserved"
  if vid==506: return "American Science & Engineering"
  if vid==507: return "Accutron Controls International Inc."
  if vid==508: return "Norcott Technologies Ltd"
  if vid==509: return "TB Woods, Inc"
  if vid==510: return "Proportion-Air, Inc."
  if vid==511: return "SICK Stegmann GmbH"
  if vid==512: return "Reserved"
  if vid==513: return "Edwards Signaling"
  if vid==514: return "Sumitomo Metal Industries, Ltd"
  if vid==515: return "Cosmo Instruments Co., Ltd."
  if vid==516: return "Denshosha Co., Ltd."
  if vid==517: return "Kaijo Corp."
  if vid==518: return "Michiproducts Co., Ltd."
  if vid==519: return "Miura Corporation"
  if vid==520: return "TG Information Network Co., Ltd."
  if vid==521: return "Fujikin , Inc."
  if vid==522: return "Estic Corp."
  if vid==523: return "GS Hydraulic Sales"
  if vid==524: return "Reserved"
  if vid==525: return "MTE Limited"
  if vid==526: return "Hyde Park Electronics, Inc."
  if vid==527: return "Pfeiffer Vacuum GmbH"
  if vid==528: return "Cyberlogic Technologies"
  if vid==529: return "OKUMA Corporation FA Systems Division"
  if vid==530: return "Reserved"
  if vid==531: return "Hitachi Kokusai Electric Co., Ltd."
  if vid==532: return "SHINKO TECHNOS Co., Ltd."
  if vid==533: return "Itoh Electric Co., Ltd."
  if vid==534: return "Colorado Flow Tech Inc."
  if vid==535: return "Love Controls Division/Dwyer Inst."
  if vid==536: return "Alstom Drives and Controls"
  if vid==537: return "The Foxboro Company"
  if vid==538: return "Tescom Corporation"
  if vid==539: return "Reserved"
  if vid==540: return "Atlas Copco Controls UK"
  if vid==541: return "Reserved"
  if vid==542: return "Autojet Technologies"
  if vid==543: return "Prima Electronics S.p.A."
  if vid==544: return "PMA GmbH"
  if vid==545: return "Shimafuji Electric Co., Ltd"
  if vid==546: return "Oki Electric Industry Co., Ltd"
  if vid==547: return "Kyushu Matsushita Electric Co., Ltd"
  if vid==548: return "Nihon Electric Wire & Cable Co., Ltd"
  if vid==549: return "Tsuken Electric Ind Co., Ltd"
  if vid==550: return "Tamadic Co."
  if vid==551: return "MAATEL SA"
  if vid==552: return "OKUMA America"
  if vid==553: return "Control Techniques PLC-NA"
  if vid==554: return "TPC Wire & Cable"
  if vid==555: return "ATI Industrial Automation"
  if vid==556: return "Microcontrol (Australia) Pty Ltd"
  if vid==557: return "Serra Soldadura, S.A."
  if vid==558: return "Southwest Research Institute"
  if vid==559: return "Cabinplant International"
  if vid==560: return "Sartorius Mechatronics T&H GmbH"
  if vid==561: return "Comau S.p.A. Robotics & Final Assembly Division"
  if vid==562: return "Phoenix Contact"
  if vid==563: return "Yokogawa MAT Corporation"
  if vid==564: return "asahi sangyo co., ltd."
  if vid==565: return "Reserved"
  if vid==566: return "Akita Myotoku Ltd."
  if vid==567: return "OBARA Corp."
  if vid==568: return "Suetron Electronic GmbH"
  if vid==569: return "Reserved"
  if vid==570: return "Serck Controls Limited"
  if vid==571: return "Fairchild Industrial Products Company"
  if vid==572: return "ARO S.A."
  if vid==573: return "M2C GmbH"
  if vid==574: return "Shin Caterpillar Mitsubishi Ltd."
  if vid==575: return "Santest Co., Ltd."
  if vid==576: return "Cosmotechs Co., Ltd."
  if vid==577: return "Hitachi Electric Systems"
  if vid==578: return "Smartscan Ltd"
  if vid==579: return "Woodhead Software & Electronics France"
  if vid==580: return "Athena Controls, Inc."
  if vid==581: return "Syron Engineering & Manufacturing, Inc."
  if vid==582: return "Asahi Optical Co., Ltd."
  if vid==583: return "Sansha Electric Mfg. Co., Ltd."
  if vid==584: return "Nikki Denso Co., Ltd."
  if vid==585: return "Star Micronics, Co., Ltd."
  if vid==586: return "Ecotecnia Socirtat Corp."
  if vid==587: return "AC Technology Corp."
  if vid==588: return "West Instruments Limited"
  if vid==589: return "NTI Limited"
  if vid==590: return "Delta Computer Systems, Inc."
  if vid==591: return "FANUC Ltd."
  if vid==592: return "Hearn-Gu Lee"
  if vid==593: return "ABB Automation Products"
  if vid==594: return "Orion Machinery Co., Ltd."
  if vid==595: return "Reserved"
  if vid==596: return "Wire-Pro, Inc."
  if vid==597: return "Beijing Huakong Technology Co. Ltd."
  if vid==598: return "Yokoyama Shokai Co., Ltd."
  if vid==599: return "Toyogiken Co., Ltd."
  if vid==600: return "Coester Equipamentos Eletronicos Ltda."
  if vid==601: return "Reserved"
  if vid==602: return "Electroplating Engineers of Japan Ltd."
  if vid==603: return "ROBOX S.p.A."
  if vid==604: return "Spraying Systems Company"
  if vid==605: return "Benshaw Inc."
  if vid==606: return "ZPA-DP A.S."
  if vid==607: return "Wired Rite Systems"
  if vid==608: return "Tandis Research, Inc."
  if vid==609: return "SSD Drives GmbH"
  if vid==610: return "ULVAC Japan Ltd."
  if vid==611: return "DYNAX Corporation"
  if vid==612: return "Nor-Cal Products, Inc."
  if vid==613: return "Aros Electronics AB"
  if vid==614: return "Jun-Tech Co., Ltd."
  if vid==615: return "HAN-MI Co. Ltd."
  if vid==616: return "uniNtech (formerly SungGi Internet)"
  if vid==617: return "Hae Pyung Electronics Reserch Institute"
  if vid==618: return "Milwaukee Electronics"
  if vid==619: return "OBERG Industries"
  if vid==620: return "Parker Hannifin/Compumotor Division"
  if vid==621: return "TECHNO DIGITAL CORPORATION"
  if vid==622: return "Network Supply Co., Ltd."
  if vid==623: return "Union Electronics Co., Ltd."
  if vid==624: return "Tritronics Services PM Ltd."
  if vid==625: return "Rockwell Automation-Sprecher+Schuh"
  if vid==626: return "Matsushita Electric Industrial Co., Ltd/Motor Co."
  if vid==627: return "Rolls-Royce Energy Systems, Inc."
  if vid==628: return "JEONGIL INTERCOM CO., LTD"
  if vid==629: return "Interroll Corp."
  if vid==630: return "Hubbell Wiring Device-Kellems (Delaware)"
  if vid==631: return "Intelligent Motion Systems"
  if vid==632: return "Reserved"
  if vid==633: return "INFICON AG"
  if vid==634: return "Hirschmann, Inc."
  if vid==635: return "The Siemon Company"
  if vid==636: return "YAMAHA Motor Co. Ltd."
  if vid==637: return "aska corporation"
  if vid==638: return "Woodhead Connectivity"
  if vid==639: return "Trimble AB"
  if vid==640: return "Murrelektronik GmbH"
  if vid==641: return "Creatrix Labs, Inc."
  if vid==642: return "TopWorx"
  if vid==643: return "Kumho Industrial Co., Ltd."
  if vid==644: return "Wind River Systems, Inc."
  if vid==645: return "Bihl & Wiedemann GmbH"
  if vid==646: return "Harmonic Drive Systems Inc."
  if vid==647: return "Rikei Corporation"
  if vid==648: return "BL Autotec, Ltd."
  if vid==649: return "Hana Information & Technology Co., Ltd."
  if vid==650: return "Seoil Electric Co., Ltd."
  if vid==651: return "Fife Corporation"
  if vid==652: return "Shanghai Electrical Apparatus Research Institute"
  if vid==653: return "Reserved"
  if vid==654: return "Parasense Development Centre"
  if vid==655: return "Reserved"
  if vid==656: return "Reserved"
  if vid==657: return "Six Tau S.p.A."
  if vid==658: return "Aucos GmbH"
  if vid==659: return "Rotork Controls"
  if vid==660: return "Automationdirect.com"
  if vid==661: return "Thermo BLH"
  if vid==662: return "System Controls, Ltd."
  if vid==663: return "Univer S.p.A."
  if vid==664: return "MKS-Tenta Technology"
  if vid==665: return "Lika Electronic SNC"
  if vid==666: return "Mettler-Toledo, Inc."
  if vid==667: return "DXL USA Inc."
  if vid==668: return "Rockwell Automation/Entek IRD Intl."
  if vid==669: return "Nippon Otis Elevator Company"
  if vid==670: return "Sinano Electric, Co., Ltd."
  if vid==671: return "Sony Manufacturing Systems"
  if vid==672: return "Reserved"
  if vid==673: return "Contec Co., Ltd."
  if vid==674: return "Automated Solutions"
  if vid==675: return "Controlweigh"
  if vid==676: return "Reserved"
  if vid==677: return "Fincor Electronics"
  if vid==678: return "Cognex Corporation"
  if vid==679: return "Qualiflow"
  if vid==680: return "Weidmuller, Inc."
  if vid==681: return "Morinaga Milk Industry Co., Ltd."
  if vid==682: return "Takagi Industrial Co., Ltd."
  if vid==683: return "Wittenstein AG"
  if vid==684: return "Sena Technologies, Inc."
  if vid==685: return "Reserved"
  if vid==686: return "APV Products Unna"
  if vid==687: return "Creator Teknisk Utvedkling AB"
  if vid==688: return "Reserved"
  if vid==689: return "Mibu Denki Industrial Co., Ltd."
  if vid==690: return "Takamastsu Machineer Section"
  if vid==691: return "Startco Engineering Ltd."
  if vid==692: return "Reserved"
  if vid==693: return "Holjeron"
  if vid==694: return "ALCATEL High Vacuum Technology"
  if vid==695: return "Taesan LCD Co., Ltd."
  if vid==696: return "POSCON"
  if vid==697: return "VMIC"
  if vid==698: return "Matsushita Electric Works, Ltd."
  if vid==699: return "IAI Corporation"
  if vid==700: return "Horst GmbH"
  if vid==701: return "MicroControl GmbH & Co."
  if vid==702: return "Leine & Linde AB"
  if vid==703: return "Reserved"
  if vid==704: return "EC Elettronica Srl"
  if vid==705: return "VIT Software HB"
  if vid==706: return "Bronkhorst High-Tech B.V."
  if vid==707: return "Optex Co., Ltd."
  if vid==708: return "Yosio Electronic Co."
  if vid==709: return "Terasaki Electric Co., Ltd."
  if vid==710: return "Sodick Co., Ltd."
  if vid==711: return "MTS Systems Corporation-Automation Division"
  if vid==712: return "Mesa Systemtechnik"
  if vid==713: return "SHIN HO SYSTEM Co., Ltd."
  if vid==714: return "Goyo Electronics Co, Ltd."
  if vid==715: return "Loreme"
  if vid==716: return "SAB Brockskes GmbH & Co. KG"
  if vid==717: return "Trumpf Laser GmbH + Co. KG"
  if vid==718: return "Niigata Electronic Instruments Co., Ltd."
  if vid==719: return "Yokogawa Digital Computer Corporation"
  if vid==720: return "O.N. Electronic Co., Ltd."
  if vid==721: return "Industrial Control  Communication, Inc."
  if vid==722: return "ABB, Inc."
  if vid==723: return "ElectroWave USA, Inc."
  if vid==724: return "Industrial Network Controls, LLC"
  if vid==725: return "KDT Systems Co., Ltd."
  if vid==726: return "SEFA Technology Inc."
  if vid==727: return "Nippon POP Rivets and Fasteners Ltd."
  if vid==728: return "Yamato Scale Co., Ltd."
  if vid==729: return "Zener Electric"
  if vid==730: return "GSE Scale Systems"
  if vid==731: return "ISAS (Integrated Switchgear & Sys. Pty Ltd)"
  if vid==732: return "Beta LaserMike Limited"
  if vid==733: return "TOEI Electric Co., Ltd."
  if vid==734: return "Hakko Electronics Co., Ltd"
  if vid==735: return "Reserved"
  if vid==736: return "RFID, Inc."
  if vid==737: return "Adwin Corporation"
  if vid==738: return "Osaka Vacuum, Ltd."
  if vid==739: return "A-Kyung Motion, Inc."
  if vid==740: return "Camozzi S.P. A."
  if vid==741: return "Crevis Co., LTD"
  if vid==742: return "Rice Lake Weighing Systems"
  if vid==743: return "Linux Network Services"
  if vid==744: return "KEB Antriebstechnik GmbH"
  if vid==745: return "Hagiwara Electric Co., Ltd."
  if vid==746: return "Glass Inc. International"
  if vid==747: return "Reserved"
  if vid==748: return "DVT Corporation"
  if vid==749: return "Woodward Governor"
  if vid==750: return "Mosaic Systems, Inc."
  if vid==751: return "Laserline GmbH"
  if vid==752: return "COM-TEC, Inc."
  if vid==753: return "Weed Instrument"
  if vid==754: return "Prof-face European Technology Center"
  if vid==755: return "Fuji Automation Co., Ltd."
  if vid==756: return "Matsutame Co., Ltd."
  if vid==757: return "Hitachi Via Mechanics, Ltd."
  if vid==758: return "Dainippon Screen Mfg. Co. Ltd."
  if vid==759: return "FLS Automation A/S"
  if vid==760: return "ABB Stotz Kontakt GmbH"
  if vid==761: return "Technical Marine Service"
  if vid==762: return "Advanced Automation Associates, Inc."
  if vid==763: return "Baumer Ident GmbH"
  if vid==764: return "Tsubakimoto Chain Co."
  if vid==765: return "Reserved"
  if vid==766: return "Furukawa Co., Ltd."
  if vid==767: return "Active Power"
  if vid==768: return "CSIRO Mining Automation"
  if vid==769: return "Matrix Integrated Systems"
  if vid==770: return "Digitronic Automationsanlagen GmbH"
  if vid==771: return "SICK STEGMANN Inc."
  if vid==772: return "TAE-Antriebstechnik GmbH"
  if vid==773: return "Electronic Solutions"
  if vid==774: return "Rocon L.L.C."
  if vid==775: return "Dijitized Communications Inc."
  if vid==776: return "Asahi Organic Chemicals Industry Co., Ltd."
  if vid==777: return "Hodensha"
  if vid==778: return "Harting, Inc. NA"
  if vid==779: return "Kubler GmbH"
  if vid==780: return "Yamatake Corporation"
  if vid==781: return "JEOL"
  if vid==782: return "Yamatake Industrial Systems Co., Ltd."
  if vid==783: return "HAEHNE Elektronische Messgerate GmbH"
  if vid==784: return "Ci Technologies Pty Ltd (for Pelamos Industries)"
  if vid==785: return "N. SCHLUMBERGER & CIE"
  if vid==786: return "Teijin Seiki Co., Ltd."
  if vid==787: return "DAIKIN Industries, Ltd"
  if vid==788: return "RyuSyo Industrial Co., Ltd."
  if vid==789: return "SAGINOMIYA SEISAKUSHO, INC."
  if vid==790: return "Seishin Engineering Co., Ltd."
  if vid==791: return "Japan Support System Ltd."
  if vid==792: return "Decsys"
  if vid==793: return "Metronix Messgerate u. Elektronik GmbH"
  if vid==794: return "Reserved"
  if vid==795: return "Vaccon Company, Inc."
  if vid==796: return "Siemens Energy & Automation, Inc."
  if vid==797: return "Ten X Technology, Inc."
  if vid==798: return "Tyco Electronics"
  if vid==799: return "Delta Power Electronics Center"
  if vid==800: return "Denker"
  if vid==801: return "Autonics Corporation"
  if vid==802: return "JFE Electronic Engineering Pty. Ltd."
  if vid==803: return "Reserved"
  if vid==804: return "Electro-Sensors, Inc."
  if vid==805: return "Digi International, Inc."
  if vid==806: return "Texas Instruments"
  if vid==807: return "ADTEC Plasma Technology Co., Ltd"
  if vid==808: return "SICK AG"
  if vid==809: return "Ethernet Peripherals, Inc."
  if vid==810: return "Animatics Corporation"
  if vid==811: return "Reserved"
  if vid==812: return "Process Control Corporation"
  if vid==813: return "SystemV. Inc."
  if vid==814: return "Danaher Motion SRL"
  if vid==815: return "SHINKAWA Sensor Technology, Inc."
  if vid==816: return "Tesch GmbH & Co. KG"
  if vid==817: return "Reserved"
  if vid==818: return "Trend Controls Systems Ltd."
  if vid==819: return "Guangzhou ZHIYUAN Electronic Co., Ltd."
  if vid==820: return "Mykrolis Corporation"
  if vid==821: return "Bethlehem Steel Corporation"
  if vid==822: return "KK ICP"
  if vid==823: return "Takemoto Denki Corporation"
  if vid==824: return "The Montalvo Corporation"
  if vid==825: return "Reserved"
  if vid==826: return "LEONI Special Cables GmbH"
  if vid==827: return "Reserved"
  if vid==828: return "ONO SOKKI CO.,LTD."
  if vid==829: return "Rockwell Samsung Automation"
  if vid==830: return "SHINDENGEN ELECTRIC MFG. CO. LTD"
  if vid==831: return "Origin Electric Co. Ltd."
  if vid==832: return "Quest Technical Solutions, Inc."
  if vid==833: return "LS Cable, Ltd."
  if vid==834: return "Enercon-Nord Electronic GmbH"
  if vid==835: return "Northwire Inc."
  if vid==836: return "Engel Elektroantriebe GmbH"
  if vid==837: return "The Stanley Works"
  if vid==838: return "Celesco Transducer Products, Inc."
  if vid==839: return "Chugoku Electric Wire and Cable Co."
  if vid==840: return "Kongsberg Simrad AS"
  if vid==841: return "Panduit Corporation"
  if vid==842: return "Spellman High Voltage Electronics Corp."
  if vid==843: return "Kokusai Electric Alpha Co., Ltd."
  if vid==844: return "Brooks Automation, Inc."
  if vid==845: return "ANYWIRE CORPORATION"
  if vid==846: return "Honda Electronics Co. Ltd"
  if vid==847: return "REO Elektronik AG"
  if vid==848: return "Fusion UV Systems, Inc."
  if vid==849: return "ASI Advanced Semiconductor Instruments GmbH"
  if vid==850: return "Datalogic, Inc."
  if vid==851: return "SoftPLC Corporation"
  if vid==852: return "Dynisco Instruments LLC"
  if vid==853: return "WEG Industrias SA"
  if vid==854: return "Frontline Test Equipment, Inc."
  if vid==855: return "Tamagawa Seiki Co., Ltd."
  if vid==856: return "Multi Computing Co., Ltd."
  if vid==857: return "RVSI"
  if vid==858: return "Commercial Timesharing Inc."
  if vid==859: return "Tennessee Rand Automation LLC"
  if vid==860: return "Wacogiken Co., Ltd"
  if vid==861: return "Reflex Integration Inc."
  if vid==862: return "Siemens AG, A&D PI Flow Instruments"
  if vid==863: return "G. Bachmann Electronic GmbH"
  if vid==864: return "NT International"
  if vid==865: return "Schweitzer Engineering Laboratories"
  if vid==866: return "ATR Industrie-Elektronik GmbH Co."
  if vid==867: return "PLASMATECH Co., Ltd"
  if vid==868: return "Reserved"
  if vid==869: return "GEMU GmbH & Co. KG"
  if vid==870: return "Alcorn McBride Inc."
  if vid==871: return "MORI SEIKI CO., LTD"
  if vid==872: return "NodeTech Systems Ltd"
  if vid==873: return "Emhart Teknologies"
  if vid==874: return "Cervis, Inc."
  if vid==875: return "FieldServer Technologies (Div Sierra Monitor Corp)"
  if vid==876: return "NEDAP Power Supplies"
  if vid==877: return "Nippon Sanso Corporation"
  if vid==878: return "Mitomi Giken Co., Ltd."
  if vid==879: return "PULS GmbH"
  if vid==880: return "Reserved"
  if vid==881: return "Japan Control Engineering Ltd"
  if vid==882: return "Embedded Systems Korea (Former Zues Emtek Co Ltd.)"
  if vid==883: return "Automa SRL"
  if vid==884: return "Harms+Wende GmbH & Co KG"
  if vid==885: return "SAE-STAHL GmbH"
  if vid==886: return "Microwave Data Systems"
  if vid==887: return "Bernecker + Rainer Industrie-Elektronik GmbH"
  if vid==888: return "Hiprom Technologies"
  if vid==889: return "Reserved"
  if vid==890: return "Nitta Corporation"
  if vid==891: return "Kontron Modular Computers GmbH"
  if vid==892: return "Marlin Controls"
  if vid==893: return "ELCIS s.r.l."
  if vid==894: return "Acromag, Inc."
  if vid==895: return "Avery Weigh-Tronix"
  if vid==896: return "Reserved"
  if vid==897: return "Reserved"
  if vid==898: return "Reserved"
  if vid==899: return "Practicon Ltd"
  if vid==900: return "Schunk GmbH & Co. KG"
  if vid==901: return "MYNAH Technologies"
  if vid==902: return "Defontaine Groupe"
  if vid==903: return "Emerson Process Management Power & Water Solutions"
  if vid==904: return "F.A. Elec"
  if vid==905: return "Hottinger Baldwin Messtechnik GmbH"
  if vid==906: return "Coreco Imaging, Inc."
  if vid==907: return "London Electronics Ltd."
  if vid==908: return "HSD SpA"
  if vid==909: return "Comtrol Corporation"
  if vid==910: return "TEAM, S.A. (Tecnica Electronica de Automatismo Y Medida)"
  if vid==911: return "MAN B&W Diesel Ltd. Regulateurs Europa"
  if vid==912: return "Reserved"
  if vid==913: return "Reserved"
  if vid==914: return "Micro Motion, Inc."
  if vid==915: return "Eckelmann AG"
  if vid==916: return "Hanyoung Nux"
  if vid==917: return "Ransburg Industrial Finishing KK"
  if vid==918: return "Kun Hung Electric Co. Ltd."
  if vid==919: return "Brimos wegbebakening b.v."
  if vid==920: return "Nitto Seiki Co., Ltd"
  if vid==921: return "PPT Vision, Inc."
  if vid==922: return "Yamazaki Machinery Works"
  if vid==923: return "SCHMIDT Technology GmbH"
  if vid==924: return "Parker Hannifin SpA (SBC Division)"
  if vid==925: return "HIMA Paul Hildebrandt GmbH"
  if vid==926: return "RivaTek, Inc."
  if vid==927: return "Misumi Corporation"
  if vid==928: return "GE Multilin"
  if vid==929: return "Measurement Computing Corporation"
  if vid==930: return "Jetter AG"
  if vid==931: return "Tokyo Electronics Systems Corporation"
  if vid==932: return "Togami Electric Mfg. Co., Ltd."
  if vid==933: return "HK Systems"
  if vid==934: return "CDA Systems Ltd."
  if vid==935: return "Aerotech Inc."
  if vid==936: return "JVL Industrie Elektronik A/S"
  if vid==937: return "NovaTech Process Solutions LLC"
  if vid==938: return "Reserved"
  if vid==939: return "Cisco Systems"
  if vid==940: return "Grid Connect"
  if vid==941: return "ITW Automotive Finishing"
  if vid==942: return "HanYang System"
  if vid==943: return "ABB K.K. Technical Center"
  if vid==944: return "Taiyo Electric Wire & Cable Co., Ltd."
  if vid==945: return "Reserved"
  if vid==946: return "SEREN IPS INC"
  if vid==947: return "Belden CDT Electronics Division"
  if vid==948: return "ControlNet International"
  if vid==949: return "Gefran S.P.A."
  if vid==950: return "Jokab Safety AB"
  if vid==951: return "SUMITA OPTICAL GLASS, INC."
  if vid==952: return "Biffi Italia srl"
  if vid==953: return "Beck IPC GmbH"
  if vid==954: return "Copley Controls Corporation"
  if vid==955: return "Fagor Automation S. Coop."
  if vid==956: return "DARCOM"
  if vid==957: return "Frick Controls (div. of York International)"
  if vid==958: return "SymCom, Inc."
  if vid==959: return "Infranor"
  if vid==960: return "Kyosan Cable, Ltd."
  if vid==961: return "Varian Vacuum Technologies"
  if vid==962: return "Messung Systems"
  if vid==963: return "Xantrex Technology, Inc."
  if vid==964: return "StarThis Inc."
  if vid==965: return "Chiyoda Co., Ltd."
  if vid==966: return "Flowserve Corporation"
  if vid==967: return "Spyder Controls Corp."
  if vid==968: return "IBA AG"
  if vid==969: return "SHIMOHIRA ELECTRIC MFG.CO.,LTD"
  if vid==970: return "Reserved"
  if vid==971: return "Siemens L&A"
  if vid==972: return "Micro Innovations AG"
  if vid==973: return "Switchgear & Instrumentation"
  if vid==974: return "PRE-TECH CO., LTD."
  if vid==975: return "National Semiconductor"
  if vid==976: return "Invensys Process Systems"
  if vid==977: return "Ametek HDR Power Systems"
  if vid==978: return "Reserved"
  if vid==979: return "TETRA-K Corporation"
  if vid==980: return "C & M Corporation"
  if vid==981: return "Siempelkamp Maschinen"
  if vid==982: return "Reserved"
  if vid==983: return "Daifuku America Corporation"
  if vid==984: return "Electro-Matic Products Inc."
  if vid==985: return "BUSSAN MICROELECTRONICS CORP."
  if vid==986: return "ELAU AG"
  if vid==987: return "Hetronic USA"
  if vid==988: return "NIIGATA POWER SYSTEMS Co., Ltd."
  if vid==989: return "Software Horizons Inc."
  if vid==990: return "B3 Systems, Inc."
  if vid==991: return "Moxa Networking Co., Ltd."
  if vid==992: return "Reserved"
  if vid==993: return "S4 Integration"
  if vid==994: return "Elettro Stemi S.R.L."
  if vid==995: return "AquaSensors"
  if vid==996: return "Ifak System GmbH"
  if vid==997: return "SANKEI MANUFACTURING Co.,LTD."
  if vid==998: return "Emerson Network Power Co., Ltd."
  if vid==999: return "Fairmount Automation, Inc."
  if vid==1000: return "Bird Electronic Corporation"
  if vid==1001: return "Nabtesco Corporation"
  if vid==1002: return "AGM Electronics, Inc."
  if vid==1003: return "ARCX Inc."
  if vid==1004: return "DELTA I/O Co."
  if vid==1005: return "Chun IL Electric Ind. Co."
  if vid==1006: return "N-Tron"
  if vid==1007: return "Nippon Pneumatics/Fludics System CO.,LTD."
  if vid==1008: return "DDK Ltd."
  if vid==1009: return "Seiko Epson Corporation"
  if vid==1010: return "Halstrup-Walcher GmbH"
  if vid==1011: return "ITT"
  if vid==1012: return "Ground Fault Systems bv"
  if vid==1013: return "Scolari Engineering S.p.A."
  if vid==1014: return "Vialis Traffic bv"
  if vid==1015: return "Weidmueller Interface GmbH & Co. KG"
  if vid==1016: return "Shanghai Sibotech Automation Co. Ltd"
  if vid==1017: return "AEG Power Supply Systems GmbH"
  if vid==1018: return "Komatsu Electronics Inc."
  if vid==1019: return "Souriau"
  if vid==1020: return "Baumuller Chicago Corp."
  if vid==1021: return "J. Schmalz GmbH"
  if vid==1022: return "SEN Corporation"
  if vid==1023: return "Korenix Technology Co. Ltd"
  if vid==1024: return "Cooper Power Tools"
  if vid==1025: return "INNOBIS"
  if vid==1026: return "Shinho System"
  if vid==1027: return "Xm Services Ltd."
  if vid==1028: return "KVC Co., Ltd."
  if vid==1029: return "Sanyu Seiki Co., Ltd."
  if vid==1030: return "TuxPLC"
  if vid==1031: return "Northern Network Solutions"
  if vid==1032: return "Converteam GmbH"
  if vid==1033: return "Symbol Technologies"
  if vid==1034: return "S-TEAM Lab"
  if vid==1035: return "Maguire Products, Inc."
  if vid==1036: return "AC&T"
  if vid==1037: return "MITSUBISHI HEAVY INDUSTRIES, LTD. KOBE SHIPYARD & MACHINERY WORKS"
  if vid==1038: return "Hurletron Inc."
  if vid==1039: return "Chunichi Denshi Co., Ltd"
  if vid==1040: return "Cardinal Scale Mfg. Co."
  if vid==1041: return "BTR NETCOM via RIA Connect, Inc."
  if vid==1042: return "Base2"
  if vid==1043: return "ASRC Aerospace"
  if vid==1044: return "Beijing Stone Automation"
  if vid==1045: return "Changshu Switchgear Manufacture Ltd."
  if vid==1046: return "METRONIX Corp."
  if vid==1047: return "WIT"
  if vid==1048: return "ORMEC Systems Corp."
  if vid==1049: return "ASATech (China) Inc."
  if vid==1050: return "Controlled Systems Limited"
  if vid==1051: return "Mitsubishi Heavy Ind. Digital System Co., Ltd. (M.H.I.)"
  if vid==1052: return "Electrogrip"
  if vid==1053: return "TDS Automation"
  if vid==1054: return "T&C Power Conversion, Inc."
  if vid==1055: return "Robostar Co., Ltd"
  if vid==1056: return "Scancon A/S"
  if vid==1057: return "Haas Automation, Inc."
  if vid==1058: return "Eshed Technology"
  if vid==1059: return "Delta Electronic Inc."
  if vid==1060: return "Innovasic Semiconductor"
  if vid==1061: return "SoftDEL Systems Limited"
  if vid==1062: return "FiberFin, Inc."
  if vid==1063: return "Nicollet Technologies Corp."
  if vid==1064: return "B.F. Systems"
  if vid==1065: return "Empire Wire and Supply LLC"
  if vid==1066: return "Reserved"
  if vid==1067: return "Elmo Motion Control LTD"
  if vid==1068: return "Reserved"
  if vid==1069: return "Asahi Keiki Co., Ltd."
  if vid==1070: return "Joy Mining Machinery"
  if vid==1071: return "MPM Engineering Ltd"
  if vid==1072: return "Wolke Inks & Printers GmbH"
  if vid==1073: return "Mitsubishi Electric Engineering Co., Ltd."
  if vid==1074: return "COMET AG"
  if vid==1075: return "Real Time Objects & Systems, LLC"
  if vid==1076: return "MISCO Refractometer"
  if vid==1077: return "JT Engineering Inc."
  if vid==1078: return "Automated Packing Systems"
  if vid==1079: return "Niobrara R&D Corp."
  if vid==1080: return "Garmin Ltd."
  if vid==1081: return "Japan Mobile Platform Co., Ltd"
  if vid==1082: return "Advosol Inc."
  if vid==1083: return "ABB Global Services Limited"
  if vid==1084: return "Sciemetric Instruments Inc."
  if vid==1085: return "Tata Elxsi Ltd."
  if vid==1086: return "TPC Mechatronics, Co., Ltd."
  if vid==1087: return "Cooper Bussmann"
  if vid==1088: return "Trinite Automatisering B.V."
  if vid==1089: return "Peek Traffic B.V."
  if vid==1090: return "Acrison, Inc"
  if vid==1091: return "Applied Robotics, Inc."
  if vid==1092: return "FireBus Systems, Inc."
  if vid==1093: return "Beijing Sevenstar Huachuang Electronics"
  if vid==1094: return "Magnetek"
  if vid==1095: return "Microscan"
  if vid==1096: return "Air Water Inc."
  if vid==1097: return "Sensopart Industriesensorik GmbH"
  if vid==1098: return "Tiefenbach Control Systems GmbH"
  if vid==1099: return "INOXPA S.A"
  if vid==1100: return "Zurich University of Applied Sciences"
  if vid==1101: return "Ethernet Direct"
  if vid==1102: return "GSI-Micro-E Systems"
  if vid==1103: return "S-Net Automation Co., Ltd."
  if vid==1104: return "Power Electronics S.L."
  if vid==1105: return "Renesas Technology Corp."
  if vid==1106: return "NSWCCD-SSES"
  if vid==1107: return "Porter Engineering Ltd."
  if vid==1108: return "Meggitt Airdynamics, Inc."
  if vid==1109: return "Inductive Automation"
  if vid==1110: return "Neural ID"
  if vid==1111: return "EEPod LLC"
  if vid==1112: return "Hitachi Industrial Equipment Systems Co., Ltd."
  if vid==1113: return "Salem Automation"
  if vid==1114: return "port GmbH"
  if vid==1115: return "B & PLUS"
  if vid==1116: return "Graco Inc."
  if vid==1117: return "Altera Corporation"
  if vid==1118: return "Technology Brewing Corporation"
  if vid==1119: return "CSE Servelec"
  if vid==1120: return "Fluke Networks"
  if vid==1121: return "Tetra Pak Packaging Solutions SPA"
  if vid==1122: return "Racine Federated, Inc."
  if vid==1123: return "Pureron Japan Co., Ltd."
  if vid==1124: return "Brother Industries, Ltd."
  if vid==1125: return "Leroy Automation"
  if vid==1126: return "THK CO., LTD."
  if vid==1127: return "TR-Electronic GmbH"
  if vid==1128: return "ASCON S.p.A."
  if vid==1129: return "Toledo do Brasil Industria de Balancas Ltda."
  if vid==1130: return "Bucyrus DBT Europe GmbH"
  if vid==1131: return "Emerson Process Management Valve Automation"
  if vid==1132: return "Alstom Transport"
  if vid==1133: return "Matrox Electronic Systems"
  if vid==1134: return "Littelfuse"
  if vid==1135: return "PLASMART, Inc."
  if vid==1136: return "Miyachi Corporation"
  if vid==1137: return "Promess Incorporated"
  if vid==1138: return "COPA-DATA GmbH"
  if vid==1139: return "Precision Engine Controls Corporation"
  if vid==1140: return "Alga Automacao e controle LTDA"
  if vid==1141: return "U.I. Lapp GmbH"
  if vid==1142: return "ICES"
  if vid==1143: return "Philips Lighting bv"
  if vid==1144: return "Aseptomag AG"
  if vid==1145: return "ARC Informatique"
  if vid==1146: return "Hesmor GmbH"
  if vid==1147: return "Kobe Steel, Ltd."
  if vid==1148: return "FLIR Systems"
  if vid==1149: return "Simcon A/S"
  if vid==1150: return "COPALP"
  if vid==1151: return "Zypcom, Inc."
  if vid==1152: return "Swagelok"
  if vid==1153: return "Elspec"
  if vid==1154: return "ITT Water & Wastewater AB"
  if vid==1155: return "Kunbus GmbH Industrial Communication"
  if vid==1156: return "Performance Controls, Inc."
  if vid==1157: return "ACS Motion Control, Ltd."
  if vid==1158: return "IStar Technology Limited"
  if vid==1159: return "Alicat Scientific, Inc."
  if vid==1160: return "ADFweb.com SRL"
  if vid==1161: return "Tata Consultancy Services Limited"
  if vid==1162: return "CXR Ltd."
  if vid==1163: return "Vishay Nobel AB"
  if vid==1164: return "SolaHD"
  if vid==1165: return "Endress+Hauser"
  if vid==1166: return "Bartec GmbH"
  if vid==1167: return "AccuSentry, Inc."
  if vid==1168: return "Exlar Corporation"
  if vid==1169: return "ILS Technology"
  if vid==1170: return "Control Concepts Inc."
  if vid==1171: return "Procon Engineering Limited"
  if vid==1172: return "Hermary Opto Electronics Inc."
  if vid==1173: return "Q-Lambda"
  if vid==1174: return "VAMP Ltd"
  if vid==1175: return "FlexLink"
  if vid==1176: return "Office FA.com Co., Ltd."
  if vid==1177: return "SPMC (Changzhou) Co. Ltd."
  if vid==1178: return "Anton Paar GmbH"
  if vid==1179: return "Zhuzhou CSR Times Electric Co., Ltd."
  if vid==1180: return "DeStaCo"
  if vid==1181: return "Synrad, Inc"
  if vid==1182: return "Bonfiglioli Vectron GmbH"
  if vid==1183: return "Pivotal Systems"
  if vid==1184: return "TKSCT"
  if vid==1185: return "Randy Nuernberger"
  if vid==1186: return "CENTRALP"
  if vid==1187: return "Tengen Group"
  if vid==1188: return "OES, Inc."
  if vid==1189: return "Actel Corporation"
  if vid==1190: return "Monaghan Engineering, Inc."
  if vid==1191: return "wenglor sensoric gmbh"
  if vid==1192: return "HSA Systems"
  if vid==1193: return "MK Precision Co., Ltd."
  if vid==1194: return "Tappan Wire and Cable"
  if vid==1195: return "Heinzmann GmbH & Co. KG"
  if vid==1196: return "Process Automation International Ltd."
  if vid==1197: return "Secure Crossing"
  if vid==1198: return "SMA Railway Technology GmbH"
  if vid==1199: return "FMS Force Measuring Systems AG"
  if vid==1200: return "ABT Endustri Enerji Sistemleri Sanayi Tic. Ltd. Sti."
  if vid==1201: return "MagneMotion Inc."
  if vid==1202: return "STS Co., Ltd."
  if vid==1203: return "MERAK SIC, SA"
  if vid==1204: return "ABOUNDI, Inc."
  if vid==1205: return "Rosemount Inc."
  if vid==1206: return "GEA FES, Inc."
  if vid==1207: return "TMG Technologie und Engineering GmbH"
  if vid==1208: return "embeX GmbH"
  if vid==1209: return "GH Electrotermia, S.A."
  if vid==1210: return "Tolomatic"
  if vid==1211: return "Dukane"
  if vid==1212: return "Elco (Tian Jin) Electronics Co., Ltd."
  if vid==1213: return "Jacobs Automation"
  if vid==1214: return "Noda Radio Frequency Technologies Co., Ltd."
  if vid==1215: return "MSC Tuttlingen GmbH"
  if vid==1216: return "Hitachi Cable Manchester"
  if vid==1217: return "ACOREL SAS"
  if vid==1218: return "Global Engineering Solutions Co., Ltd."
  if vid==1219: return "ALTE Transportation, S.L."
  if vid==1220: return "Penko Engineering B.V."

  