CIPTypes = {0x00: (0, "UNKNOWN", '?'),
            0xa0: (88, "STRUCT", '<B'),
            0xc1: (1, "BOOL", '?'),
            0xc2: (1, "SINT", '<b'),
            0xc3: (2, "INT", '<h'),
            0xc4: (4, "DINT", '<i'),
            0xc5: (8, "LINT", '<q'),
            0xc6: (1, "USINT", '<B'),
            0xc7: (2, "UINT", '<H'),
            0xc8: (4, "UDINT", '<I'),
            0xc9: (8, "LWORD", '<Q'),
            0xca: (4, "REAL", '<f'),
            0xcb: (8, "LREAL", '<d'),
            0xd3: (4, "DWORD", '<i'),
            0xda: (1, "STRING", '<B')}
